### ISSUE TITLE
Suggestion: Use deep linking to allow users to click direct urls to join game

### ISSUE THREAD

**Issue by Uular** [Moetto/frisbeer-bot#3]
Use [deep linking](https://core.telegram.org/bots#deep-linking) when posting messages to the notification group, so that users start a private conversation with the bot instead of posting the command to that group.

The link could simply be something like `t.me/bot_name?start=GameNameHere`, or a more specific query string to allow for other instant commands also.

**Comment by Moetto** [comment]
Done. Game creation, join and leave messages all contain link to join game
